config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: redirect('/home')

  resources :likes, only: [:create, :destroy]
  resources :dislikes, only: [:create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home', to: 'posts#index', as: 'home'
  get 'favorite', to: 'posts#favorite', as: 'favorite'

  get 'users', to: 'users#index', as: 'users'
  post 'users', to: 'users#create'
  get 'users/:id/settings', to: 'users#edit', as: 'settings'
  get 'users/:id', to: 'users#show', as: 'user'
  patch 'users/:id', to: 'users#update'

  get 'users/:user_id/posts/new', to: 'posts#new', as:  'new_post'
  post 'users/:user_id/posts', to: 'posts#create'
  get 'users/:user_id/posts', to: 'posts#index', as: 'posts' 
  get 'users/:user_id/posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  get 'users/:user_id/posts/:id', to: 'posts#show', as: 'detail_post'
  get 'users/:user_id/posts/:id/save', to: 'posts#save', as: 'save_post'
  patch 'users/:user_id/posts/:id', to: 'posts#update'
  delete 'users/:user_id/posts/:id', to: 'posts#destroy'
  

  get 'users/:user_id/posts/:post_id/comments', to: 'comments#index', as: 'post_comments'
  get 'users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_post_comment'
  post 'users/:user_id/posts/:post_id/comments', to: 'comments#create'
  get 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#show', as: 'post_comment'
  patch 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#update'
  delete 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy'
  put 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#update'
  get 'users/:user_id/posts/:post_id/comments/:id/edit', to: 'comments#edit', as: 'edit_post_comment'

### JK ###
  # get 'users', to: 'users#index', as: 'users'
  # post 'users', to: 'users#create'
  # get 'users/:id/settings', to: 'users#edit', as: 'settings'
  # get 'users/:id', to: 'users#show', as: 'user'
  # patch 'users/:id', to: 'users#update'

  # post 'posts', to: 'posts#create'
  # get 'posts/new', to: 'posts#new', as:  'new_post'
  # get 'posts', to: 'posts#index', as: 'posts' 
  # get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  # get 'posts/:id', to: 'posts#show', as: 'detail_post'
  # get 'posts/:id/save', to: 'posts#save', as: 'save_post'
  # patch 'posts/:id', to: 'posts#update'
  # delete 'posts/:id', to: 'posts#destroy'
  

  # get 'posts/:post_id/comments', to: 'comments#index', as: 'post_comments'
  # get 'posts/:post_id/comments/new', to: 'comments#new', as: 'new_post_comment'
  # post 'posts/:post_id/comments', to: 'comments#create'
  # get 'posts/:post_id/comments/:id', to: 'comments#show', as: 'post_comment'
  # patch 'posts/:post_id/comments/:id', to: 'comments#update'
  # delete 'posts/:post_id/comments/:id', to: 'comments#destroy'
  # put 'posts/:post_id/comments/:id', to: 'comments#update'
  # get 'posts/:post_id/comments/:id/edit', to: 'comments#edit', as: 'edit_post_comment'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :bigint           not null, primary key
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  post_id     :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_comments_on_post_id              (post_id)
#  index_comments_on_user_id              (user_id)
#  index_comments_on_user_id_and_post_id  (user_id,post_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord

  belongs_to(
    :post,
    class_name: 'Post',
    foreign_key: 'post_id',
    inverse_of: :comments
  )

  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: 'user_id',
    inverse_of: :comments
  )
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_post

  def index
      @user = User.find(params[:user_id])
      # @post = @user.posts.find(params[:post_id])
      @post = Post.find(params[:post_id])
      @comments = @post.comments
      render :index
    end

  def show
      @post = Post.find(params[:post_id])
      @comment = @post.comments.order(created_at: :desc)
      render :show
  end

  def new
      @post = Post.find(params[:post_id])
      @comment = Comment.new
      render :new
  end



  # def create
  #     @post = Post.find(params[:post_id])
  #     @comment = @post.comments.create(params.require(:comment).permit(:comment, :user_id, :post_id, :description))
  #     @comment.users = current.user
  #     if @comment.save
  #       flash[:success] = "Comment saved successfully"
  #       redirect_to post_comments_url(@post)
  #     else
  #       flash.now[:error] = "Comment could not be saved"
  #       render :new
  #     end
  #   end




##new add##
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:success] = "Comment saved successfully"
      redirect_to post_comments_url(@user, @post)
    else
      flash.now[:error] = "Comment could not be saved"
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:description)
  end

  # def set_post
  #   @post = Post.find(params[:post_id])
  # end
##new add##

  def edit
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      render :edit
  end

  def update
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      if @comment.update(params.require(:comment).permit(:comment, :user_id, :post_id, :description))
        flash[:success] = "Comment updated successfully"
        redirect_to post_comment_url(@post, @comment)
      else
        flash.now[:error] = "Comment could not be updated"
        render :edit
      end
    end

  def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      flash[:success] = "Comment deleted successfully"
      redirect_to post_comments_url(@post)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<%# <link rel = "stylesheet" href = "style.css">
<link rel = "stylesheet" href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

<div class = "share-btn-container">
    <a href = "#" class="facebook-btn">
        <i class="fab fa-facebook"></i>
    </a>

    <a href = "#" class="twitter-btn">
        <i class="fab fa-twitter"></i>
    </a>

    <a href = "#" class="instagram-btn">
        <i class="fab fa-instagram"></i>
    </a>

   <a href = "#" class="pinteres-btn">
        <i class="fab fa-pinterest"></i>
    </a>

    <a href = "#" class="whatsapp-btn">
        <i class="fab fa-whatsapp"></i>
    </a>

</div>  %>


<p>
  <%= link_to 'Back to Post', detail_post_path(@user, @post), class: 'btn btn-secondary',style: 'margin-top:20px'%>
</p>

<h1 style = "margin-bottom:40px"> Comments To Post</h1></p>

<%= bootstrap_form_with model: @comment, url: post_comments_path, method: :post, local: true do |t| %>

    <style>
        #inline
        {
            width:25%;
            height:20px;
            /* display:flex; */
            /* float: left */
        } 
        .one
        {
            width:20%; 
            height:100px;
            margin:10px
        } 
        .two
        {
            width:100%;
            height:20px;
            margin:10px;
            font-size:12px;
            line-height: 30%
            
        }

        .three
        {
            width:100%;
            height:50px;
            position:relative;
            left:150px;
            margin:10px;
            font-size:18px

        }
    </style>

<% @comments.each do |t| %>

     <div id="inline"> 
        <div class="two">
            <p><%= t.user.username %></p>
            <p><%= t.created_at.strftime("%m/%d/%Y") %></p>
        </div> 
    </div> 

        <div class='col'>
            <div class='three'>

               <i><p> <%= t.description %></i></p> 
            </div> 
        </div>  
<% end %>   



        <td> <%= link_to "I want to comment", new_post_comment_path, class: "btn btn-primary", style: 'margin-top:40px'%> </td> 
        <p><button type="button" class="btn btn-danger" style = "margin-top:10px">Cancel</button></p>
   
<%end%>

app/views/comments/new.html.erb
<p>
  <%= link_to 'Back to Post', posts_path(@post), class: 'btn btn-secondary',style: 'margin-top:20px'%>
</p>

<h1 style = "margin-bottom:40px"> Your Comments To the Post</h1></p>

<%= bootstrap_form_with model: @comment, url: post_comments_path, method: :post, local: true do |t| %>

        <%= t.text_area :description, label: "Leave Your Comment Here:" %>
        <%= t.submit "Confirm My Comments", class: "btn btn-primary" %>

<% end %>