config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: redirect('/home')

  resources :likes, only: [:create, :destroy]
  resources :dislikes, only: [:create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home', to: 'posts#index', as: 'home'
  get 'favorite', to: 'posts#favorite', as: 'favorite'

  get 'users', to: 'users#index', as: 'users'
  post 'users', to: 'users#create'
  get 'users/:id/settings', to: 'users#edit', as: 'settings'
  get 'users/:id', to: 'users#show', as: 'user'
  patch 'users/:id', to: 'users#update'

  get 'users/:user_id/posts/new', to: 'posts#new', as:  'new_post'
  post 'users/:user_id/posts', to: 'posts#create'
  get 'users/:user_id/posts', to: 'posts#index', as: 'posts' 
  get 'users/:user_id/posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  get 'users/:user_id/posts/:id', to: 'posts#show', as: 'detail_post'
  get 'users/:user_id/posts/:id/save', to: 'posts#save', as: 'save_post'
  patch 'users/:user_id/posts/:id', to: 'posts#update'
  delete 'users/:user_id/posts/:id', to: 'posts#destroy'
  

  get 'users/:user_id/posts/:post_id/comments', to: 'comments#index', as: 'post_comments'
  get 'users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_post_comment'
  post 'users/:user_id/posts/:post_id/comments', to: 'comments#create'
  get 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#show', as: 'post_comment'
  patch 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#update'
  delete 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy'
  put 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#update'
  get 'users/:user_id/posts/:post_id/comments/:id/edit', to: 'comments#edit', as: 'edit_post_comment'

### JK ###
  # get 'users', to: 'users#index', as: 'users'
  # post 'users', to: 'users#create'
  # get 'users/:id/settings', to: 'users#edit', as: 'settings'
  # get 'users/:id', to: 'users#show', as: 'user'
  # patch 'users/:id', to: 'users#update'

  # post 'posts', to: 'posts#create'
  # get 'posts/new', to: 'posts#new', as:  'new_post'
  # get 'posts', to: 'posts#index', as: 'posts' 
  # get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  # get 'posts/:id', to: 'posts#show', as: 'detail_post'
  # get 'posts/:id/save', to: 'posts#save', as: 'save_post'
  # patch 'posts/:id', to: 'posts#update'
  # delete 'posts/:id', to: 'posts#destroy'
  

  # get 'posts/:post_id/comments', to: 'comments#index', as: 'post_comments'
  # get 'posts/:post_id/comments/new', to: 'comments#new', as: 'new_post_comment'
  # post 'posts/:post_id/comments', to: 'comments#create'
  # get 'posts/:post_id/comments/:id', to: 'comments#show', as: 'post_comment'
  # patch 'posts/:post_id/comments/:id', to: 'comments#update'
  # delete 'posts/:post_id/comments/:id', to: 'comments#destroy'
  # put 'posts/:post_id/comments/:id', to: 'comments#update'
  # get 'posts/:post_id/comments/:id/edit', to: 'comments#edit', as: 'edit_post_comment'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  description            :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  image                  :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  mount_uploader :image, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many(
    :posts,
    class_name: 'Post', 
    foreign_key: 'user_id',
    inverse_of: :user,
    dependent: :destroy
  )

  has_many(
    :comments,
    class_name: 'Comment', 
    foreign_key: 'user_id',
    inverse_of: :user,
    dependent: :destroy
  )

  has_many :likes
  
  has_many :dislikes

  has_many(
    :saved_posts,
    class_name: 'SavedPost',
    foreign_key: 'user_id',
    inverse_of: :user,
    dependent: :destroy
  )

  has_many(
    :saved_posts,
    class_name: 'SavedPost',
    foreign_key: 'save_user_id',
    inverse_of: :save_user,
    dependent: :destroy
  )

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
		render :index
	end

	def new
		@user = User.new
		render :new
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts
		@saved_posts = @user.saved_posts
		render :show
	end

	def edit
		@user = User.find(params[:id])
		render :edit
	end

	def create
		@user = User.new(params.require(:user).permit(:username, :password, :email, :image, :description))
	    if @user.save
			flash[:success] = "New User Created!"
			redirect_to users_url
		  else
			flash.now[:error] = "User creation failed"
			render :new
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(params.require(:user).permit(:username, :password, :email, :image, :description))
		  flash[:success] = "Your information successfully updated!"
		  redirect_to user_url(@user)
		else
		  flash.now[:error] = "Your information update failed"
		  render :edit
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Settings</h1>

<%= bootstrap_form_with model: @user, url: user_path(@user), method: :patch, local: true do |f| %>

	<%= f.text_field :username, label: "Change my user name" %>
	<%= f.email_field :email, label: "Change my email"  %>
	<%= f.file_field :image, label: "Change my profile picture"  %>
	<%= f.text_area :description, label: "Change my bio" %>
	<%= f.submit "Save"%>

<% end %>

<%= link_to "Delete My Account", user_path(@user) %><br>
<%= link_to "Sign Out", users_path %>

app/views/users/index.html.erb
<h1>User Items</h1>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Image</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
    	<td><%= image_tag(user.image_url)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<style>
    #inline
    {
        width:25%;
        height:100px;
        display:flex;
        float: left
    } 
    .one
    {
        width:20%;
        height:100px;
        margin:10px
    } 
    .two
    {
        width:50%;
        height:100px;
        margin:10px
    }
</style>

<div class="d-flex">
  <div class="p-2"><%= image_tag @user.image_url, :class => "img-fluid float-left", :style => "height: 7vh; width: 5vw"%></div>
  <div class="p-2"><b style="font-size:20px"><%= @user.username %></b></div>
	<% if user_signed_in? && current_user.id == @user.id %>
  		<div class="ml-auto p-2"><%= link_to "Settings",  settings_path(@user), :class => "btn btn-secondary"%></div>
	<% else %>
		<div class="ml-auto p-2"></div></div>
	<% end %>
</div>
<div class="d-flex">
  <div class="p-2"><%= @user.description %></div>
</div>

<div class="row justify-content-center">
	<p class="col "></p>
	<p class="col "></p>
	<p onclick = "s(false)" class="col btn btn-primary" >My Posts</p>
	<p onclick = "s(true)" class="col btn btn-primary" >Saved Posts</p>
	<p class="col"></p>
	<p class="col"></p>
</div>

<div id='posts'>
<% @posts.each do |p| %>
	<div id="inline"> 
            <div class="one">
                <a>
                    <%= link_to user_path(p.user) do %>
                        <%= image_tag p.user.image_url, :class => "img-fluid float-left", :style => "height: 7vh; width: 5vw"%>
                    <% end %>
                </a>
            </div> 
            <div class="two">
                <p><b style="font-size:17px"><%= p.user.username %></b></p>
                <p><%= p.created_at.strftime("%m/%d/%Y") %></p>
            </div> 
        </div> 

	<div class='row '>
		<div class='col'></div>
		<div class='col'>
			<div class='row justify-content-center'>
				<a>
					<%= link_to detail_post_path(p.user, p) do %>
						<%= image_tag p.image_url, class: 'w-250 shadow-lg d-block mx-auto', style: 'max-width: 750px; max-height: 750px'%>
					<% end %>
				</a>
			</div>
		<div class='row'> 
		<div class='col'>
			<strong style="font-size:20px"><%= p.name%></strong>
			<p><i style="font-size:18px">Rating: <%= p.rating 
			%></i></p>
		</div>  
		</div>
		</div>
		<div class='col'></div>
	</div>
<% end %>
</div>

<div id='saved_posts'>
<% @saved_posts.each do |p| %>
	<div id="inline" style='visibility: visible'> 
		<div class="one" style='visibility: visible'>
			<a>
                    <%= link_to user_path(p.user) do %>
                        <%= image_tag p.user.image_url, :class => "img-fluid float-left", :style => "height: 7vh; width: 5vw"%>
                    <% end %>
            </a>
		</div> 
		<div class="two" style='visibility: visible'>
				<p><b style="font-size:17px"><%= p.user.username %></b></p>
                <p><%= p.created_at.strftime("%m/%d/%Y") %></p>
		</div> 
	</div> 

	<div class='row ' style='visibility: visible'>
		<div class='col'></div>
		<div class='col'>
			<div class='row justify-content-center' style='visibility: visible'>
				<a>
					<%= link_to detail_post_path(p.user, p) do %>
						<%= image_tag p.post.image_url, class: 'w-250 shadow-lg d-block mx-auto', style: 'max-width: 750px; max-height: 750px'%>
					<% end %>
				</a>
			</div>
		<div class='row'> 
		<div class='col' style='visibility: visible'>
			<strong style="font-size:20px"><%= p.post.name%></strong>
			<p><i style="font-size:18px">Rating: <%= p.post.rating 
			%></i></p>
		</div>  
		</div>
		</div>
		<div class='col'></div>
	</div>
	<% end  %>
</div>

<script type="text/javascript">

	function hide (elements) {
		elements = elements.length ? elements : [elements];
		for (var index = 0; index < elements.length; index++) {
			elements[index].style.display = 'none';
		}
	}
	function show (elements) {
		elements = elements.length ? elements : [elements];
		for (var index = 0; index < elements.length; index++) {
			elements[index].style.display = '';
		}
	}
	function s(saved) {
		console.log(document.getElementById("posts").style.display);
		if (saved) {
			hide(document.getElementById("posts"))
			show(document.getElementById("saved_posts"))
		}else{
			show(document.getElementById("posts"))
			hide(document.getElementById("saved_posts"))
		}
	}
	window.onload = function() {
		hide(document.getElementById("saved_posts"))
	};
	$( document ).ready(function() {
		hide(document.getElementById("saved_posts"))
	});
</script>