config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: redirect('/home')

  resources :likes, only: [:create, :destroy]
  resources :dislikes, only: [:create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home', to: 'posts#index', as: 'home'
  get 'favorite', to: 'posts#favorite', as: 'favorite'

  get 'users', to: 'users#index', as: 'users'
  post 'users', to: 'users#create'
  get 'users/:id/settings', to: 'users#edit', as: 'settings'
  get 'users/:id', to: 'users#show', as: 'user'
  patch 'users/:id', to: 'users#update'

  get 'users/:user_id/posts/new', to: 'posts#new', as:  'new_post'
  post 'users/:user_id/posts', to: 'posts#create'
  get 'users/:user_id/posts', to: 'posts#index', as: 'posts' 
  get 'users/:user_id/posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  get 'users/:user_id/posts/:id', to: 'posts#show', as: 'detail_post'
  get 'users/:user_id/posts/:id/save', to: 'posts#save', as: 'save_post'
  patch 'users/:user_id/posts/:id', to: 'posts#update'
  delete 'users/:user_id/posts/:id', to: 'posts#destroy'
  

  get 'users/:user_id/posts/:post_id/comments', to: 'comments#index', as: 'post_comments'
  get 'users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_post_comment'
  post 'users/:user_id/posts/:post_id/comments', to: 'comments#create'
  get 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#show', as: 'post_comment'
  patch 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#update'
  delete 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy'
  put 'users/:user_id/posts/:post_id/comments/:id', to: 'comments#update'
  get 'users/:user_id/posts/:post_id/comments/:id/edit', to: 'comments#edit', as: 'edit_post_comment'

### JK ###
  # get 'users', to: 'users#index', as: 'users'
  # post 'users', to: 'users#create'
  # get 'users/:id/settings', to: 'users#edit', as: 'settings'
  # get 'users/:id', to: 'users#show', as: 'user'
  # patch 'users/:id', to: 'users#update'

  # post 'posts', to: 'posts#create'
  # get 'posts/new', to: 'posts#new', as:  'new_post'
  # get 'posts', to: 'posts#index', as: 'posts' 
  # get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  # get 'posts/:id', to: 'posts#show', as: 'detail_post'
  # get 'posts/:id/save', to: 'posts#save', as: 'save_post'
  # patch 'posts/:id', to: 'posts#update'
  # delete 'posts/:id', to: 'posts#destroy'
  

  # get 'posts/:post_id/comments', to: 'comments#index', as: 'post_comments'
  # get 'posts/:post_id/comments/new', to: 'comments#new', as: 'new_post_comment'
  # post 'posts/:post_id/comments', to: 'comments#create'
  # get 'posts/:post_id/comments/:id', to: 'comments#show', as: 'post_comment'
  # patch 'posts/:post_id/comments/:id', to: 'comments#update'
  # delete 'posts/:post_id/comments/:id', to: 'comments#destroy'
  # put 'posts/:post_id/comments/:id', to: 'comments#update'
  # get 'posts/:post_id/comments/:id/edit', to: 'comments#edit', as: 'edit_post_comment'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light", style="font-size: 18px">
    <a class="navbar-brand" href="#" style="font-size:30px">Wing Watchers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= active_class(home_path) %>">
                <%= link_to 'Home', home_path, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= active_class(home_path) %>">
                <%= link_to 'Favorite', favorite_path, class: 'nav-link' %>
            </li>
             <% if user_signed_in? %>
                <li class="nav-item <%= active_class(home_path) %>">
                    <%= link_to 'Post New Review', new_post_path(current_user), class: 'nav-link' %>
                </li>
            <% end %>
        </ul>

        <ul class="navbar-nav">
            <% if user_signed_in? %>
                <li class="nav-item <%= active_class(edit_user_registration_path) %>">
                    <%= link_to "Hello, #{current_user.username}", user_path(current_user), class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Not you?', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </li>
            
            <% else %>
                <li class="nav-item <%= active_class(new_user_session_path) %>">
                    <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
                </li>
                <li class="nav-item <%= active_class(new_user_registration_path) %>">
                    <%= link_to 'Not a Member yet?', new_user_registration_path, class: 'nav-link' %>
                </li>
            
            <% end %>
        </ul>
    </div>
</nav>